### ISSUE TITLE
Snipets?

### ISSUE THREAD

**Issue by PossumLover** [n00bzorz/Daily-and-weekly-notes#1]
Do you plan to add your snipets? I really like how you've made your design look, and would love to see the code to implement something like it into my vault.

**Comment by PossumLover** [comment]
Oops wrong button. Sorry, I really don't know how to use github. I hope you can still see this.

**Comment by n00bzorz** [comment]
So sorry i didnt see this, started a new job. ill post up some now (one.....sec? hour or so? llol sorry!)

**Comment by n00bzorz** [comment]
> Oops wrong button. Sorry, I really don't know how to use github. I hope you can still see this.

Alright , 'I've got up my newest version of my daily note I'm running ATM and the snippets that I've made to be used in my vault. any other snippets used would be from the plug ins i have listed in the readme.  Sorry it took so long, i had forgotten all about this O_O

**Comment by n00bzorz** [comment]
LMK IF THERE IS ANYTHINK ELSE YOU WOULD LIKE
